---
notification:
  email:
  - mrkn@ruby-lang.org

language: ruby

before_install:
  - gem install bundler -v 1.17.2

script:
  - rake travis
  - rake install

matrix:
  include:
    - name: "2.4"
      rvm: 2.4.5
    - name: "2.5"
      rvm: 2.5.2
    - name: "2.6"
      rvm: 2.6
    - name: "trunk"
      rvm: ruby-head
